### ISSUE TITLE
Pin Repositories to the Org Page

### ISSUE THREAD

**Issue by VerisimilitudeX** [NuevoFoundation/.github#1]
The .github README looks awesome - great work @jeremiahjordanisaacson! Another enhancement would be to pin repositories instead of using the default 'Popular Repositories'.

**Benefit:** This would ensure that users aren't confused by any unnecessary repositories showing up on the main page (e.g., the .github repo).

 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/96280466/183506401-76dc583c-2aa9-4388-9381-083994ba731e.png">

**Comment by jeremiahjordanisaacson** [comment]
Fixed. ;)
